// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrvfVqFzkRFFMPaSHE-Zr8X6kvX_dltq8',
    appId: '1:997125753161:web:2a27a056f1481ada3d7298',
    messagingSenderId: '997125753161',
    projectId: 'jaga-app-40db8',
    authDomain: 'jaga-app-40db8.firebaseapp.com',
    storageBucket: 'jaga-app-40db8.firebasestorage.app',
    measurementId: 'G-N3WFZXC7L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7C6qe9W86MIN8ChYvW2bz1ubvxPy2m2M',
    appId: '1:997125753161:android:7e41032de1e261c03d7298',
    messagingSenderId: '997125753161',
    projectId: 'jaga-app-40db8',
    storageBucket: 'jaga-app-40db8.firebasestorage.app',
  );

}