// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-cBfMHb-Yb5L2UCO-r0wrR-djP47FZI',
    appId: '1:934100035583:web:8347aa3b52d733318aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    authDomain: 'jaga-app-3e0ef.firebaseapp.com',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
    measurementId: 'G-RYBGT0GD9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-nT0ttF7CvwqceqadkBazlIuQI0xG-4',
    appId: '1:934100035583:android:4af337129ed489208aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
  );

}